### PR TITLE
Add integration with Travis CI

### LINKED ISSUE #14: Add integration with Travis CI
Please configure integration with TravisCI:
* [ ] [Enable repo testing in TravisCI](https://travis-ci.com/kpi-web-guild/django-girls-blog-igorkruglyak)
* [ ] Add TravisCI badge (master branch) to `README.md` with a single commit. (click Build Status next to octocat icon on [this page](https://travis-ci.com/kpi-web-guild/django-girls-blog-igorkruglyak))
* [ ] Create new branch called `feature/travis-ci-integration` and do all the following steps within that branch.
* [ ] Add `.travis.yml` using `pre-commit` as a script. Set it up to run Python 3.7 env and add PIP caching. Ensure you install `pre-commit` before running tests:
```yaml
language: python
python: 3.7
cache: pip
before_install: pip install -U pre-commit
script: pre-commit run --all-files
```
* [ ] Push the branch and create a Pull Request for it.

### PR DESCRIPTION
**Pull request by igorkruglyak**
Closes #14

This commit includes the configure integration with TravisCI

### CODE REVIEW

**Review by webknjaz — CHANGES_REQUESTED** [review]
This PR contains unrelated changes. Remove them from the related branch.

**Comment by igorkruglyak** [comment]
> This PR contains unrelated changes. Remove them from the related branch.

I have to remove files .gitattributes, .gitignore, .pre-commit-config.yaml from the branch feature/travis-ci-integration?

**Comment by webknjaz** [comment]
You have to remove commits introducing those changes from the branch. This is because each PR should be atomic and solve only one task.

**Comment by igorkruglyak** [comment]
> This PR contains unrelated changes. Remove them from the related branch.

I have to remove files .gitattributes, .gitignore, .pre-commit-config.yaml from the branch feature/travis-ci-integration?

**Comment by webknjaz** [comment]
Don't close the PR, just fix the branch

**Pull request closed without merging**
