### PR TITLE
Add integration with Travis CI

### LINKED ISSUE #14: Add integration with Travis CI
Please configure integration with TravisCI:
* [ ] [Enable repo testing in TravisCI](https://travis-ci.com/kpi-web-guild/django-girls-blog-igorkruglyak)
* [ ] Add TravisCI badge (master branch) to `README.md` with a single commit. (click Build Status next to octocat icon on [this page](https://travis-ci.com/kpi-web-guild/django-girls-blog-igorkruglyak))
* [ ] Create new branch called `feature/travis-ci-integration` and do all the following steps within that branch.
* [ ] Add `.travis.yml` using `pre-commit` as a script. Set it up to run Python 3.7 env and add PIP caching. Ensure you install `pre-commit` before running tests:
```yaml
language: python
python: 3.7
cache: pip
before_install: pip install -U pre-commit
script: pre-commit run --all-files
```
* [ ] Push the branch and create a Pull Request for it.

### PR DESCRIPTION
**Pull request by igorkruglyak**
Closes #14

This commit includes the configure integration with TravisCI

### CODE REVIEW

**Comment by igorkruglyak** [comment]
What is my mistake again?

**Comment by webknjaz** [comment]
You don't need a commit removing files. You just have to change the one you have not to add them + you removed a config which is already in master but we still need it there. You can use interactive rebase to edit the history of this branch.

**Comment by webknjaz** [comment]
What will happen to master if you merge this?

**Review by webknjaz — APPROVED** [review]

**Comment by webknjaz** [comment]
​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​ ​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​

**Pull request merged**
